name: CI/CD for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY_USERNAME }}/experiment:latest .
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker push ${{ secrets.REGISTRY_USERNAME }}/experiment:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Azure Web Apps
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'actionsexperiment'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.REGISTRY_USERNAME }}/flask-app:latest'
